### 
GET http://localhost:3003/shopper/user/maycon

###
GET http://localhost:3003/shopper/user/products/580f22bd-7f79-406a-aec3-2caf61477d4f

###
GET http://localhost:3003/shopper/products

### 
GET http://localhost:3003/shopper/user/products

###
GET http://localhost:3003/shopper/product/total/price/4149fd68-6ceb-4e1c-baf9-395397aa6427

###
POST http://localhost:3003/shopper/user/products
Content-Type: application/json

{
    "id_product": 45,
    "id_user": "4149fd68-6ceb-4e1c-baf9-395397aa6427"
}
###
POST http://localhost:3003/shopper/user
Content-Type: application/json

{
    "name": "teste2",
    "delivery_date": "2022-10-01"
}

###
PUT http://localhost:3003/shopper/user/19/8

###
DELETE http://localhost:3003/shopper/user/products/16
